"""Verified Memory Gate — governance and verification before agent memory writes."""

from verified_memory_gate.audit_log import (
    AppendOnlyAuditLog,
    AuditEventKind,
    AuditRecord,
    VerifierAudit,
)
from verified_memory_gate.coordinator import EDVCoordinator
from verified_memory_gate.edv import (
    DistillContext,
    Distiller,
    EDVPipeline,
    EDVPipelineResult,
    EDVStageResult,
    ExecuteBundle,
    ExecuteStage,
    ExecutorTrace,
    RuleBasedDistiller,
    STAGE_DISTILL,
    STAGE_EXECUTE,
    STAGE_VERIFY,
    StageOutput,
    VerifyStage,
    WindowBinding,
)
from verified_memory_gate.gate import GateMode, MemoryGate
from verified_memory_gate.gatemem_episodes import (
    SUBSET_EPISODES,
    Checkpoint,
    CheckpointCategory,
    Episode,
)
from verified_memory_gate.gatemem_harness import (
    CheckpointResult,
    GateMemAgentStub,
    GateMemThresholds,
    HarnessReport,
    MGSScore,
    aggregate_mgs,
    evaluate_checkpoint,
    run_episode,
    run_harness,
)
from verified_memory_gate.governance import can_read, parse_leak_targets
from verified_memory_gate.langgraph_hook import (
    DEFAULT_BLOCKED_MEMORY_TOOLS,
    STATE_BLOCKED_TOOLS,
    STATE_DISTILL_CONTEXT,
    STATE_MEMORY_REJECTIONS,
    STATE_MEMORY_RESULT,
    STATE_MEMORY_REVIEW,
    STATE_TRACES,
    BlockedToolCall,
    MemoryToolGuard,
    guard_tool_call,
    make_propose_memory_node,
    propose_memory,
    serialize_commit_result,
)
from verified_memory_gate.models import (
    CandidateExperience,
    CommitResult,
    CommitStatus,
    MemoryEntry,
    MemoryScope,
    PendingCandidate,
    RetrievalFilter,
    Tombstone,
)
from verified_memory_gate.store import InMemoryStore
from verified_memory_gate.verifiers import (
    ConsensusResult,
    QuorumConfig,
    Verifier,
    VerifierOutcome,
    VerifierRegistry,
    VerifierResult,
)

__all__ = [
    "AppendOnlyAuditLog",
    "AuditEventKind",
    "AuditRecord",
    "VerifierAudit",
    "DEFAULT_BLOCKED_MEMORY_TOOLS",
    "STATE_BLOCKED_TOOLS",
    "STATE_DISTILL_CONTEXT",
    "STATE_MEMORY_REJECTIONS",
    "STATE_MEMORY_RESULT",
    "STATE_MEMORY_REVIEW",
    "STATE_TRACES",
    "BlockedToolCall",
    "MemoryToolGuard",
    "guard_tool_call",
    "make_propose_memory_node",
    "propose_memory",
    "serialize_commit_result",
    "SUBSET_EPISODES",
    "Checkpoint",
    "CheckpointCategory",
    "CheckpointResult",
    "Episode",
    "GateMemAgentStub",
    "GateMemThresholds",
    "HarnessReport",
    "MGSScore",
    "Tombstone",
    "aggregate_mgs",
    "can_read",
    "evaluate_checkpoint",
    "parse_leak_targets",
    "run_episode",
    "run_harness",
    "CandidateExperience",
    "CommitResult",
    "CommitStatus",
    "ConsensusResult",
    "DistillContext",
    "Distiller",
    "EDVCoordinator",
    "EDVPipeline",
    "EDVPipelineResult",
    "EDVStageResult",
    "ExecuteBundle",
    "ExecuteStage",
    "ExecutorTrace",
    "GateMode",
    "InMemoryStore",
    "MemoryEntry",
    "MemoryGate",
    "MemoryScope",
    "PendingCandidate",
    "QuorumConfig",
    "RetrievalFilter",
    "RuleBasedDistiller",
    "STAGE_DISTILL",
    "STAGE_EXECUTE",
    "STAGE_VERIFY",
    "StageOutput",
    "VerifyStage",
    "Verifier",
    "VerifierOutcome",
    "VerifierRegistry",
    "VerifierResult",
    "WindowBinding",
]

__version__ = "0.1.0"
